### ISSUE TITLE
Could you tell me the parameters of execution_weight in phase 1 in Stoat ?

### ISSUE THREAD

**Issue by zhuguocheng29** [tingsu/Stoat#10]
![image](https://user-images.githubusercontent.com/10451468/61880269-29b7af80-af27-11e9-9d1b-0ae84049873d.png)

**Comment by tingsu** [comment]
Hi,

In my setting, I set alpha (the weight for widget type) as 1, beta (the weight for number of unexplored children widget) as 0.3-0.6 (because usually more number of widgets may appear when a new page is reached), gamma as 1.0-1.5 (just to amplify the effect when the event has been executed). Hope these values can give you some sense.

You can also check the code: https://github.com/tingsu/Stoat/blob/b94ce16af467b4ddb5bd4766bcd1b3b651d2360a/Stoat/a3e/bin/picker.rb#L374

See the function '''updateActionsWeight'''

**Comment by zhuguocheng29** [comment]
Thank you for your answer. I find that you also raise stoats+, but I don't find any paper in your homepage. Could you give me your paper, thank you

**Comment by tingsu** [comment]
Stoat+ is an enhanced version of Stoat. 

The enhancement can be found in the Section 5.2 of our ICSE'18 paper "Large-Scale Analysis of Framework-Specific Exceptions in Android Apps" (https://tingsu.github.io/files/icse18-crash.pdf). 

The main idea is to include more diversity of injected events.

**Comment by zhuguocheng29** [comment]
Thank you very much !
