### ISSUE TITLE
Run Stoat on AVD with Android 7.1.1, armeabi-7a image meet exception ”uiautomator server rpc not started"

### ISSUE THREAD

**Issue by muiucj** [tingsu/Stoat#14]
Hi Su, I run stoat on AVD with Android 7.1.1, armeabi-7a image meet exception ”uiautomator server rpc not started",  how to fix it ?
![image](https://user-images.githubusercontent.com/36884583/70525002-550f0400-1b81-11ea-87ac-d936b0a1983e.png)

**Comment by tingsu** [comment]
Hi,

  First, I recommend you to use the X86 image, which is much faster than the armeabi-7a image on any hardware-acceleration supported desktop (although this may not be related to the issue you encountered).

  Second, as for this issue, I think it is due to the failure of ``uiautomator`` itlself, which is used by Stoat to execute events. 

  1. Can you execute some event scripts alone to see whether this error still exists? 

  2. If this error still exists, you can comment out this code line:
https://github.com/tingsu/Stoat/blob/92fa3bbfc6e46092a2a3361696db75da71f1ea6f/Stoat/bin/run_stoat_testing.rb#L88
    In fact, this line just to naturalize the device.
    You can always start the emulator with ``-read-only`` option to test an app and comment this line. In this way, we do not need this line of code (and this issue could be removed).

   If you still have this issue, let me know.

**Comment by tingsu** [comment]
Still have this issue or solved?

**Comment by muiucj** [comment]
Hi,Su
I will try your suggestion to see whether my problem can be fixed, thank you!
