### ISSUE TITLE
Missing coverage.py

### ISSUE THREAD

**Issue by ms1995** [tingsu/Stoat#2]
From `Stoat/agentManager.rb:623`

```
merge_cov_cmd = "python #{$myConf.get_ella_tool_dir()}/coverage.py #{$myConf.get_app_dir_loc()} MCMC_#{@mcmc_iteration}"
```

It seems that `coverage.py` is not included in the repo.

**Comment by tingsu** [comment]
In the current version, we have not included the Ella tool (as a result, coverage.py, the script in the customized Ella tool, cannot be found). Ella is used to collect method coverage for testing apks (closed-source apps). But Stoat should still be able to run apks without Ella (in this case, its effectiveness may be affected due to the lack of coverage optimization metric). We will include the Ella tool in the next version soon.
