### ISSUE TITLE
Instrumented coverage Run

### ISSUE THREAD

**Issue by mmilella94** [tingsu/Stoat#7]
I have a closed-source apps, i have instrumented it with ella, which is the command that i have to run with this generated apk to generate also the coverage?(on the readme there is only the command for  non -instrumented closed apps).
Thanks

**Comment by XX-STOAT** [comment]
In the current Stoat version (the version on this github), we have not included Ella (in fact, we commented the code that interacts with Ella to collect method coverage, although we did include Ella in our FSE'17 paper's experiment).

But you still can run Stoat on the Ella-instrumented apk file (use the same command line for non-instrumented closed apps). If you want to get the coverage, you have to parse the coverage data dumped by Ella itself. 

We are trying to make our customized Ella module available on the github these days so that people can use the fully-equipped Stoat as you hoped.

Let me know if you have any concerns.

**Comment by mmilella94** [comment]
Thank you very much for the explanation
